### ISSUE TITLE
Where to put SAs?

### ISSUE THREAD

**Issue by askfriends** [MsGsuite/CloneBot_Heroku#14]
Hello;
First of all thanks for the repo its really useful.
I have created SAs but where to put them? Your heroku guide video url is dead, kindly update it

**Comment by Ryoo1** [comment]
you need to archive all the SA then zip it and send it to bot using command /sa

**Comment by askfriends** [comment]
> you need to archive all the SA then zip it and send it to bot using command /sa

Yeah got it thanks

**Comment by MsGsuite** [comment]
Yes
