### ISSUE TITLE
File missing problem

### ISSUE THREAD

**Issue by mayank629** [MsGsuite/CloneBot_Heroku#3]
Today I tried to clone a folder with 50 sub-folders. Bot says it successfully cloned the folder to my td. But when I check that folder in my td I get 39 subfolders. Then again tried with a folder of another 50 sub-folders this time bot actually cloned 45 folders and other 5 are missing. Any solution?

**Comment by MsGsuite** [comment]
Hi

I would like to upgrade ***@***.*** please.

Thanks for everything
TerreAnima

**Comment by MsGsuite** [comment]
Hi,

Sometimes it happened that some files are skipped (I don't know why).
Send the link again and the files will be copied (existing files are skipped)
