### ISSUE TITLE
How to Save Configuration 

### ISSUE THREAD

**Issue by BlackFoxy616** [MsGsuite/CloneBot_Heroku#31]
Is there any way to store that sa file and favourite drive list in this not because each time it restarts it asks for it again.

**Comment by MsGsuite** [comment]
Hi, 
It's not possible. You can host the bot in another service than heroku if you don't want it to restart every 24h

**Comment by suhiymof** [comment]
if a clone task need more than 24 hours to finish. it will never be done?
