### ISSUE TITLE
team drive

### ISSUE THREAD

**Issue by chammiii** [MsGsuite/CloneBot_Heroku#4]
![Screenshot_2021-05-22-09-52-39-200_org telegram plus](https://user-images.githubusercontent.com/23624044/119214334-a5fb8980-bae3-11eb-86f8-2f0d0ef19493.jpg)
hi,
nice repo
one problem
how to add my gmail so it shows my team drives in bot?

**Comment by MsGsuite** [comment]
Hello

You need to add exactly the same sa in the bot and as member of the destination shared drive else it won't work.
You the chat : t.me/msgsuitechat to get help.

**Comment by ladlamalik** [comment]
I am also facing he same issue
